# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Julia image as the base image
FROM julia:1.9

# Set the working directory
WORKDIR /app

# Copy the Project.toml and Manifest.toml files
COPY Project.toml /app/

# Install package dependencies
RUN julia -e 'using Pkg; Pkg.instantiate()'

# Copy the rest of the package's source code
COPY . /app

# Precompile the package
RUN julia -e 'using Pkg; Pkg.precompile()'

# Set the entrypoint to a Julia REPL
ENTRYPOINT ["julia"]
